const keysForKeyboard = [
  [
    {first: '`', second: '~', func: false, size: 1},
    {first: '1', second: '!', func: false, size: 1},
    {first: '2', second: '@', func: false, size: 1},
    {first: '3', second: '#', func: false, size: 1},
    {first: '4', second: '$', func: false, size: 1},
    {first: '5', second: '%', func: false, size: 1},
    {first: '6', second: '^', func: false, size: 1},
    {first: '7', second: '&', func: false, size: 1},
    {first: '8', second: '*', func: false, size: 1},
    {first: '9', second: '(', func: false, size: 1},
    {first: '0', second: ')', func: false, size: 1},
    {first: '-', second: '_', func: false, size: 1},
    {first: '=', second: '+', func: false, size: 1},
    {first: 'Backspace', second: '', func: true, size: 2}
  ],[
    {first: 'Tab', second: '', func: true, size: 1},
    {first: 'q', second: '', func: false, size: 1},
    {first: 'w', second: '', func: false, size: 1},
    {first: 'e', second: '', func: false, size: 1},
    {first: 'r', second: '', func: false, size: 1},
    {first: 't', second: '', func: false, size: 1},
    {first: 'y', second: '', func: false, size: 1},
    {first: 'u', second: '', func: false, size: 1},
    {first: 'i', second: '', func: false, size: 1},
    {first: 'o', second: '', func: false, size: 1},
    {first: 'p', second: '', func: false, size: 1},
    {first: '[', second: '{', func: false, size: 1},
    {first: ']', second: '}', func: false, size: 1},
    {first: 'Del', second: '', func: true, size: 2},
  ],[
    {first: 'Caps lock', second: '', func: true, size: 2},
    {first: 'a', second: '', func: false, size: 1},
    {first: 's', second: '', func: false, size: 1},
    {first: 'd', second: '', func: false, size: 1},
    {first: 'f', second: '', func: false, size: 1},
    {first: 'g', second: '', func: false, size: 1},
    {first: 'h', second: '', func: false, size: 1},
    {first: 'j', second: '', func: false, size: 1},
    {first: 'k', second: '', func: false, size: 1},
    {first: 'l', second: '', func: false, size: 1},
    {first: ';', second: ':', func: false, size: 1},
    {first: '\'', second: '"', func: false, size: 1},
    {first: '\\', second: '|', func: false, size: 1},
    {first: 'Enter', second: '', func: true, size: 2},
  ],[
    {first: 'Shift', second: '', func: true, size: 2},
    {first: 'z', second: '', func: false, size: 1},
    {first: 'x', second: '', func: false, size: 1},
    {first: 'c', second: '', func: false, size: 1},
    {first: 'v', second: '', func: false, size: 1},
    {first: 'b', second: '', func: false, size: 1},
    {first: 'n', second: '', func: false, size: 1},
    {first: 'm', second: '', func: false, size: 1},
    {first: ',', second: '<', func: false, size: 1},
    {first: '.', second: '>', func: false, size: 1},
    {first: '/', second: '?', func: false, size: 1},
    {first: '&#9650;', second: '', func: true, size: 1},
    {first: 'Shift', second: '', func: true, size: 2},
  ],[
    {first: 'Cntr', second: '', func: true, size: 1},
    {first: 'Win', second: '', func: true, size: 1},
    {first: 'Alt', second: '', func: true, size: 1},
    {first: '', second: '', func: false, size: 3},
    {first: 'Alt', second: '', func: true, size: 1},
    {first: '&#9668;', second: '', func: true, size: 1},
    {first: '&#9660;', second: '', func: true, size: 1},
    {first: '&#9658;', second: '', func: true, size: 1},
    {first: 'Cntr', second: '', func: true, size: 1},
  ]
]

export default keysForKeyboard